version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/logs_db
    depends_on:
      - db
    volumes:
      - face_images:/app/face_img

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logs_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    container_name: frontend
    ports:
      - "8080:80"

volumes:
  postgres_data:
  face_images:
